/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    products: Product;
    solutions: Solution;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    contacts: Contact;
    banner: Banner;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    banner: BannerSelect<false> | BannerSelect<true>;
  };
  locale: 'ua' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  viewType: 'home' | 'information';
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  homeBlocks?:
    | (
        | IntroBlockFields
        | GlobalTrustBlockFields
        | PreventsAttacksBlockFields
        | QuotesBlockFields
        | TailoredProtectionBlockFields
        | SolutionsBlockFields
        | WhyUsBlockFields
        | ReadyUpgradeBlockFields
        | ResourcesBlockFields
      )[]
    | null;
  privacyText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlockFields".
 */
export interface IntroBlockFields {
  title: string;
  /**
   * To highlight in red highlight the desired part of the text and press 'B'
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bgVideo: string | Media;
  advantagesList: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'intro-home-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GlobalTrustBlockFields".
 */
export interface GlobalTrustBlockFields {
  title: string;
  firstStatistic: {
    title: string;
    numbers: string;
    description: string;
  };
  statisticsList: {
    icon: string | Media;
    title: string;
    numbers: string;
    id?: string | null;
  }[];
  logoCompany: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'global-trust-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PreventsAttacksBlockFields".
 */
export interface PreventsAttacksBlockFields {
  title: string;
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prevents-attacks-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuotesBlockFields".
 */
export interface QuotesBlockFields {
  title: string;
  quotesList: {
    quote: string;
    author: string;
    position: string;
    logo: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'quotes-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TailoredProtectionBlockFields".
 */
export interface TailoredProtectionBlockFields {
  title: string;
  advantagesList: {
    title: string;
    description: string;
    image: string | Media;
    link: {
      type?: ('reference' | 'custom' | 'form') | null;
      newTab?: boolean | null;
      label: string;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
      form?: (string | null) | Form;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tailored-protection-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields: (
    | {
        name: string;
        label?: string | null;
        isRequired: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        name: string;
        label?: string | null;
        isRequired: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'email';
      }
    | {
        name: string;
        label: string;
        isRequired: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'phone-number';
      }
    | {
        name: string;
        label?: string | null;
        isRequired: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'message';
      }
  )[];
  submitButtonLabel: string;
  successMessage: string;
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}.
   */
  emails?:
    | {
        /**
         * For multiple values, separate them with a comma, for example: emailToSend1@gmail.com,emailToSend2@gmail.com
         */
        emailTo: string;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom: string;
        subject: string;
        message: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  telegramChatIds?:
    | {
        chatId: string;
        message: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionsBlockFields".
 */
export interface SolutionsBlockFields {
  title: string;
  solutionsList: {
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image: string | Media;
    link: {
      type?: ('reference' | 'custom' | 'form') | null;
      newTab?: boolean | null;
      label: string;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
      form?: (string | null) | Form;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutions-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlockFields".
 */
export interface WhyUsBlockFields {
  title: string;
  description: string;
  statisticsList: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'why-us-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadyUpgradeBlockFields".
 */
export interface ReadyUpgradeBlockFields {
  /**
   * To highlight in red highlight the desired part of the text and press 'B'
   */
  title?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description: string;
  bgVideo: string | Media;
  scheduleDemo: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  talkToExpert: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ready-upgrade-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourcesBlockFields".
 */
export interface ResourcesBlockFields {
  title: string;
  resourcesList: {
    icon: string | Media;
    title: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'resources-home-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  productBlocks?:
    | (
        | IntroProductBlockFields
        | TailoderProductBlockFields
        | WhyUsProductBlockFields
        | TrapProductBlockFields
        | StatsProductBlockFields
        | TakeStepProductBlockFields
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Генерується автоматично або відредагуйте вручну
   */
  publishedOn?: string | null;
  thumbnail: string | Media;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroProductBlockFields".
 */
export interface IntroProductBlockFields {
  title: string;
  description: string;
  bgVideo: string | Media;
  advantagesList: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'intro-product-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TailoderProductBlockFields".
 */
export interface TailoderProductBlockFields {
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tailoder-product-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsProductBlockFields".
 */
export interface WhyUsProductBlockFields {
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  advantagesList: {
    icon: string | Media;
    title: string;
    description: string;
    id?: string | null;
  }[];
  descriptionBanner: string;
  bannerImg: string | Media;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'why-us-product-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrapProductBlockFields".
 */
export interface TrapProductBlockFields {
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  advantagesList: {
    icon: string | Media;
    title: string;
    description: string;
    id?: string | null;
  }[];
  descriptionBanner?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'trap-product-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsProductBlockFields".
 */
export interface StatsProductBlockFields {
  title: string;
  description: string;
  bgImage: string | Media;
  advantagesList: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats-product-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TakeStepProductBlockFields".
 */
export interface TakeStepProductBlockFields {
  title: string;
  description: string;
  advantagesList: {
    text: string;
    icon: string | Media;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'take-step-product-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string;
  title: string;
  solutionBlocks?:
    | (
        | IntroSolutionBlockFields
        | AttackSolutionBlockFields
        | WebSolutionBlockFields
        | TakeStepProductBlockFields
        | HelpSolutionBlockFields
        | ReadySolutionBlockFields
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Генерується автоматично або відредагуйте вручну
   */
  publishedOn?: string | null;
  thumbnail: string | Media;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSolutionBlockFields".
 */
export interface IntroSolutionBlockFields {
  title: string;
  description: string;
  bgVideo: string | Media;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'intro-solution-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttackSolutionBlockFields".
 */
export interface AttackSolutionBlockFields {
  title: string;
  description: string;
  statisticsList: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'attack-solution-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebSolutionBlockFields".
 */
export interface WebSolutionBlockFields {
  title: string;
  descriptionLeft?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionRight?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bgImage: string | Media;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'web-solution-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HelpSolutionBlockFields".
 */
export interface HelpSolutionBlockFields {
  title: string;
  advantagesList: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'help-solution-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadySolutionBlockFields".
 */
export interface ReadySolutionBlockFields {
  title: string;
  description: string;
  image: string | Media;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ready-solution-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData: {
    field: string;
    value?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'solutions';
        value: string | Solution;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  viewType?: T;
  richText?: T;
  homeBlocks?:
    | T
    | {
        'intro-home-block'?: T | IntroBlockFieldsSelect<T>;
        'global-trust-block'?: T | GlobalTrustBlockFieldsSelect<T>;
        'prevents-attacks-block'?: T | PreventsAttacksBlockFieldsSelect<T>;
        'quotes-block'?: T | QuotesBlockFieldsSelect<T>;
        'tailored-protection-block'?: T | TailoredProtectionBlockFieldsSelect<T>;
        'solutions-block'?: T | SolutionsBlockFieldsSelect<T>;
        'why-us-block'?: T | WhyUsBlockFieldsSelect<T>;
        'ready-upgrade-block'?: T | ReadyUpgradeBlockFieldsSelect<T>;
        'resources-home-block'?: T | ResourcesBlockFieldsSelect<T>;
      };
  privacyText?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlockFields_select".
 */
export interface IntroBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  bgVideo?: T;
  advantagesList?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GlobalTrustBlockFields_select".
 */
export interface GlobalTrustBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  firstStatistic?:
    | T
    | {
        title?: T;
        numbers?: T;
        description?: T;
      };
  statisticsList?:
    | T
    | {
        icon?: T;
        title?: T;
        numbers?: T;
        id?: T;
      };
  logoCompany?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PreventsAttacksBlockFields_select".
 */
export interface PreventsAttacksBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuotesBlockFields_select".
 */
export interface QuotesBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  quotesList?:
    | T
    | {
        quote?: T;
        author?: T;
        position?: T;
        logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TailoredProtectionBlockFields_select".
 */
export interface TailoredProtectionBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  advantagesList?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              form?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionsBlockFields_select".
 */
export interface SolutionsBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  solutionsList?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              form?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlockFields_select".
 */
export interface WhyUsBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  statisticsList?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadyUpgradeBlockFields_select".
 */
export interface ReadyUpgradeBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  bgVideo?: T;
  scheduleDemo?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  talkToExpert?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourcesBlockFields_select".
 */
export interface ResourcesBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  resourcesList?:
    | T
    | {
        icon?: T;
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  productBlocks?:
    | T
    | {
        'intro-product-block'?: T | IntroProductBlockFieldsSelect<T>;
        'tailoder-product-block'?: T | TailoderProductBlockFieldsSelect<T>;
        'why-us-product-block'?: T | WhyUsProductBlockFieldsSelect<T>;
        'trap-product-block'?: T | TrapProductBlockFieldsSelect<T>;
        'stats-product-block'?: T | StatsProductBlockFieldsSelect<T>;
        'take-step-product-block'?: T | TakeStepProductBlockFieldsSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedOn?: T;
  thumbnail?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroProductBlockFields_select".
 */
export interface IntroProductBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  bgVideo?: T;
  advantagesList?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TailoderProductBlockFields_select".
 */
export interface TailoderProductBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsProductBlockFields_select".
 */
export interface WhyUsProductBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  advantagesList?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  descriptionBanner?: T;
  bannerImg?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrapProductBlockFields_select".
 */
export interface TrapProductBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  advantagesList?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  descriptionBanner?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsProductBlockFields_select".
 */
export interface StatsProductBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  bgImage?: T;
  advantagesList?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TakeStepProductBlockFields_select".
 */
export interface TakeStepProductBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  advantagesList?:
    | T
    | {
        text?: T;
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  solutionBlocks?:
    | T
    | {
        'intro-solution-block'?: T | IntroSolutionBlockFieldsSelect<T>;
        'attack-solution-block'?: T | AttackSolutionBlockFieldsSelect<T>;
        'web-solution-block'?: T | WebSolutionBlockFieldsSelect<T>;
        'take-step-product-block'?: T | TakeStepProductBlockFieldsSelect<T>;
        'help-solution-block'?: T | HelpSolutionBlockFieldsSelect<T>;
        'ready-solution-block'?: T | ReadySolutionBlockFieldsSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedOn?: T;
  thumbnail?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSolutionBlockFields_select".
 */
export interface IntroSolutionBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  bgVideo?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttackSolutionBlockFields_select".
 */
export interface AttackSolutionBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  statisticsList?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebSolutionBlockFields_select".
 */
export interface WebSolutionBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  descriptionLeft?: T;
  descriptionRight?: T;
  bgImage?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HelpSolutionBlockFields_select".
 */
export interface HelpSolutionBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  advantagesList?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadySolutionBlockFields_select".
 */
export interface ReadySolutionBlockFieldsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        text?:
          | T
          | {
              name?: T;
              label?: T;
              isRequired?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              isRequired?: T;
              id?: T;
              blockName?: T;
            };
        'phone-number'?:
          | T
          | {
              name?: T;
              label?: T;
              isRequired?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              name?: T;
              label?: T;
              isRequired?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  successMessage?: T;
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  telegramChatIds?:
    | T
    | {
        chatId?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'form') | null;
          newTab?: boolean | null;
          label: string;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          form?: (string | null) | Form;
        };
        isSubmenu?: boolean | null;
        submenu?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'form') | null;
                newTab?: boolean | null;
                label: string;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                form?: (string | null) | Form;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo: string | Media;
  logoGoogle: string | Media;
  logoGrow: string | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'form') | null;
          newTab?: boolean | null;
          label: string;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          form?: (string | null) | Form;
        };
        isSubmenu?: boolean | null;
        submenu?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'form') | null;
                newTab?: boolean | null;
                label: string;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                form?: (string | null) | Form;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  privacyPolicy: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  terms: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  cookies: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: string;
  email: string;
  address: string;
  gMapLink: string;
  socialLinks: {
    logo: string | Media;
    link: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: string;
  title: string;
  description: string;
  image: string | Media;
  link: {
    type?: ('reference' | 'custom' | 'form') | null;
    newTab?: boolean | null;
    label: string;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    form?: (string | null) | Form;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              form?: T;
            };
        isSubmenu?: T;
        submenu?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    form?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  logoGoogle?: T;
  logoGrow?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              form?: T;
            };
        isSubmenu?: T;
        submenu?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    form?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  privacyPolicy?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  terms?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  cookies?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  email?: T;
  address?: T;
  gMapLink?: T;
  socialLinks?:
    | T
    | {
        logo?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        form?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}